### PR TITLE
Adding 3.1.10 and 3.1.11 versions

### PR DESCRIPTION
**Pull request by bkukoyi**
**UPDATE INSTALLABLE VERSIONS**:
Updates the Guardium insights versions installable via the quictstart to the two latest versions of GI v3.1 that have currently been released. 3.1.10 and 3.1.11.

This update adds versions 3.1.10 and 3.1.11.
Tascat results and logs associated with this PR are located here: s3://babztest/taskcat-logs/
Also attached to this PR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-ibm-security-guardium-insights/files/9687152/taskcat_outputs.zip)

### CODE REVIEW

**Review by vsnyc — CHANGES_REQUESTED** [review]
Please sync with the latest main branch in the aws-quickstart org repo, revert the non-code changes in the templates, and then resubmit with only code changes (if any) in the templates. Our technical writer had previously gone through and edited all the descriptions to match our guidance.

**Comment by bkukoyi** [comment]
> Please sync with the latest main branch in the aws-quickstart org repo, revert the non-code changes in the templates, and then resubmit with only code changes (if any) in the templates. Our technical writer had previously gone through and edited all the descriptions to match our guidance.

I'm sorry @vsnyc Could you please explain what you mean by non-code changes? I only made code changes. This project was handed over to our team so I might be missing something here. I just want to make sure I understand what you're referring to.

**Comment by vsnyc** [comment]
@bkukoyi - No problems, let me know if a meeting would be helpful. The parameter labels, descriptions, etc. in the two CloudFormation templates have previously been edited by our Technical Writer. Your latest changes (perhaps done on a stale copy of the fork) are overriding that and we can't accept. I was suggesting that you sync your fork with the upstream repo (aws-quickstart/quickstart-ibm-security-guardium-insights) first and then create a PR with only the code changes (i.e. don't edit parameter descriptions unless necessary).

Here are a couple of examples (see the [diff link](https://github.com/aws-quickstart/quickstart-ibm-security-guardium-insights/pull/18/files#diff-ae50f9043ca0c2b93695b988c6e7f5c3be11e938b7742862e821cd0906342c04) for all the changes).


Property | Edited | Your version
---------|-------|------------
KeyPairName | Name of an existing public/private key pair, which allows you to securely connect to your instance after it launches. If you do not have a key pair in this AWS Region, create one before continuing. | Name of an existing public/private key pair, which allows you to securely connect to your instance after it launches. If you do not have one in this AWS Region, please create it before continuing.
NumberOfMaster | Desired number of control plane node instances | The desired capacity for the Red Hat Openshift Container Platform master node instances.
NumberOfDb2DataNodes: | Desired number of IBM Db2 data node instances. Choose "1" if the Guardium Insights production size is extra small. Choose "2" if the production size is small. Choose "3" if the production size is medium or large. Note: If the number of compute node instances exceeds your Red Hat entitlement limits or AWS instance limits, the stack will fail. Choose a number that is within your limits. | The desired capacity for the Db2 data node instances. Choose 1 if the IBM Security Guardium Insights production size is extra small. Choose 2 if the IBM Security Guardium Insights production size is small. Choose 3 if the IBM Security Guardium Insights production size is medium or large. Choose 5 if the IBM Security Guardium Insights production size is xlarge. Note: If the number of compute node instances exceeds your Red Hat entitlement limits or AWS instance limits, the stack will fail. Choose a number that is within your limits.

**Comment by vsnyc** [comment]
@bkukoyi - the changes in templates/ibm-security-guardium-insights.template.yaml look good. Could you do similar changes in the templates/ibm-security-root.template.yaml template as well? I should be able to merge after that.

**Comment by bkukoyi** [comment]
@vsnyc Please see the latest commit with the requested changes. Thanks

**Comment by vsnyc** [comment]
@bkukoyi - there were still a few remaining that I have fixed in this commit: https://github.com/aws-quickstart/quickstart-ibm-security-guardium-insights/pull/18/commits/8f79267ba03e71e08b3351c19d523dcc4d2e9f13. We're good to merge this now.

**Review by vsnyc — APPROVED** [review]

**Pull request merged**
