### PR TITLE
Update insights to 3.2 Release

### PR DESCRIPTION
**Pull request by bkukoyi**
This updates the Guardium Insights to our latest GI 3.2 Release
*Description of changes:*
Added extensive support for GI 3.2 and removed support for GI 3.1 from the Quickstart.

Taskcat output available here: https://babztest.s3.us-east-2.amazonaws.com/taskcat_outputs/

Please let me know if anything else is required @vsnyc 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vsnyc** [comment]
@bkukoyi - looks like the taskcat outputs URL is private. Could you either make it public, or attach a zip of the folder as a comment? Thanks!

**Comment by bkukoyi** [comment]
@vsnyc Here is the zipped taskcat output folder:
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-ibm-security-guardium-insights/files/10230485/taskcat_outputs.zip)

**Comment by bkukoyi** [comment]
@vsnyc Just to bring to your attention that the taskcat output is now in the comments again.

**Review by vsnyc — APPROVED** [review]

**Comment by vsnyc** [comment]
@bkukoyi - thanks, merged!

**Pull request merged**
