### PR TITLE
3.2.4 PR + template name change

### PR DESCRIPTION
**Pull request by bkukoyi**
*Issue #, if available:*

*Description of changes:*
Changes to the template name, the license naming and support for 3.2.4.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vsnyc — CHANGES_REQUESTED** [review]
@bkukoyi - Thanks for the PR. We typically keep the `.template.yaml` filename extension as that makes it easier for some IDEs to recognize these as a CloudFormation template as opposed to a generic YAML file. Is there a reason you want to rename the file to just `.yaml` instead of `.template.yaml`. We can keep just `.yaml` as well, but just wanted to make you aware of why they had the `.template.yaml` extension.

Additionally, you'll also need to change this line in [.taskcat.yml](https://github.com/aws-quickstart/quickstart-ibm-security-guardium-insights/blob/main/.taskcat.yml#L56) to point to the renamed template for the tests to work.

Lastly, could you attach output of a successful test run? Many thanks!

**Comment by bkukoyi** [comment]
> @bkukoyi - Thanks for the PR. We typically keep the `.template.yaml` filename extension as that makes it easier for some IDEs to recognize these as a CloudFormation template as opposed to a generic YAML file. Is there a reason you want to rename the file to just `.yaml` instead of `.template.yaml`. We can keep just `.yaml` as well, but just wanted to make you aware of why they had the `.template.yaml` extension.
> 
> Additionally, you'll also need to change this line in [.taskcat.yml](https://github.com/aws-quickstart/quickstart-ibm-security-guardium-insights/blob/main/.taskcat.yml#L56) to point to the renamed template for the tests to work.
> 
> Lastly, could you attach output of a successful test run? Many thanks!

I see. I'll update the names and let our PM know. Thanks for pointing that out.

**Comment by bkukoyi** [comment]
Will run the taskcat and attach the output shortly.

**Comment by bkukoyi** [comment]
@vsnyc This is ready for review

**Comment by bkukoyi** [comment]
@vsnyc Just checking in again/ Would you mid going over the PR now?

**Review by vsnyc — APPROVED** [review]

**Comment by vsnyc** [comment]
Thanks @bkukoyi - looks great!

**Pull request merged**
